### PR TITLE
Sample shop-app repaired.

### LINKED ISSUE #69: Failed to launch shop-app: Cannot start meta-application with an abstract environment
I cannot launch the sample app `shop-app`. This exception is thrown:

`Cannot start meta-application with an abstract environment`

**Full log:**

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2019-05-29 11:18:33.376  INFO 11377 --- [  restartedMain] poussecafe.shop.App                      : Starting App on tswp19 with PID 11377 (/data/bdevos/IdeaProjects/pousse-cafe/pousse-cafe-shop-app/target/classes started by bdevos in /data/bdevos/IdeaProjects/pousse-cafe)
2019-05-29 11:18:33.378 DEBUG 11377 --- [  restartedMain] poussecafe.shop.App                      : Running with Spring Boot v2.1.5.RELEASE, Spring v5.1.7.RELEASE
2019-05-29 11:18:33.378  INFO 11377 --- [  restartedMain] poussecafe.shop.App                      : No active profile set, falling back to default profiles: default
2019-05-29 11:18:33.412  INFO 11377 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-05-29 11:18:33.412  INFO 11377 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-05-29 11:18:33.869  INFO 11377 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-05-29 11:18:33.927  INFO 11377 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 53ms. Found 4 repository interfaces.
2019-05-29 11:18:34.190  INFO 11377 --- [  restartedMain] org.reflections.Reflections              : Reflections took 25 ms to scan 3 urls, producing 48 keys and 89 values 
2019-05-29 11:18:34.211 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.journal.process.StoreConsumptionResult.storeSuccessfulConsumption(poussecafe.support.model.SuccessfulConsumption)
2019-05-29 11:18:34.211 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.journal.process.StoreConsumptionResult.storeFailedConsumption(poussecafe.support.model.FailedConsumption)
2019-05-29 11:18:34.213 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.support.adapters.messaging.FailedConsumptionData
2019-05-29 11:18:34.213 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.support.adapters.messaging.SuccessfulConsumptionData
2019-05-29 11:18:34.215 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding data access implementation class poussecafe.journal.adapters.MongoJournalEntryDataAccess
2019-05-29 11:18:34.222  INFO 11377 --- [  restartedMain] org.reflections.Reflections              : Reflections took 4 ms to scan 2 urls, producing 43 keys and 119 values 
2019-05-29 11:18:34.226 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Customer poussecafe.shop.domain.CustomerFactory.createCustomer(poussecafe.shop.command.CreateCustomer)
2019-05-29 11:18:34.227 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Product poussecafe.shop.domain.ProductFactory.buildProductWithNoStock(poussecafe.shop.command.CreateProduct)
2019-05-29 11:18:34.227 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.shop.domain.Order.settle(poussecafe.shop.command.SettleOrder)
2019-05-29 11:18:34.227 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.shop.domain.Order.ship(poussecafe.shop.command.ShipOrder)
2019-05-29 11:18:34.227 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.shop.domain.Product.addUnits(poussecafe.shop.command.AddUnits)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public void poussecafe.shop.domain.Product.placeOrder(poussecafe.shop.command.PlaceOrder)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Order poussecafe.shop.domain.OrderFactory.buildPlacedOrder(poussecafe.shop.domain.OrderPlaced)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Message poussecafe.shop.domain.MessageFactory.buildMessage(poussecafe.shop.domain.OrderSettled)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Message poussecafe.shop.domain.MessageFactory.buildMessage(poussecafe.shop.domain.OrderReadyForShipping)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Message poussecafe.shop.domain.MessageFactory.buildMessage(poussecafe.shop.domain.OrderRejected)
2019-05-29 11:18:34.228 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Defining listener for method public poussecafe.shop.domain.Message poussecafe.shop.domain.MessageFactory.buildMessage(poussecafe.shop.domain.OrderCreated)
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableMessageCreated
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.CreateCustomerData
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableOrderPlaced
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SettleOrderData
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableOrderCreated
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableOrderReadyForShipping
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.ShipOrderData
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableOrderRejected
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.AddUnitsData
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.PlaceOrderData
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.SerializableOrderSettled
2019-05-29 11:18:34.230 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding message implementation class poussecafe.shop.adapters.messaging.CreateProductData
2019-05-29 11:18:34.232 DEBUG 11377 --- [  restartedMain] poussecafe.discovery.ClassPathExplorer   : Adding data implementation class poussecafe.shop.domain.mongo.CustomerData
2019-05-29 11:18:34.232 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : 3 abstract entities:
2019-05-29 11:18:34.232 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : - poussecafe.shop.domain.Message
2019-05-29 11:18:34.232 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : - poussecafe.shop.domain.Order
2019-05-29 11:18:34.232 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : - poussecafe.shop.domain.Product
2019-05-29 11:18:34.232 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : 0 abstract messages:
2019-05-29 11:18:34.233 ERROR 11377 --- [  restartedMain] p.environment.EnvironmentBuilder         : 0 abstract services:
2019-05-29 11:18:34.233  WARN 11377 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pousseCafeRuntime' defined in class path resource [poussecafe/shop/AppConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [poussecafe.runtime.Runtime]: Factory method 'pousseCafeRuntime' threw exception; nested exception is poussecafe.exception.PousseCafeException: Cannot start meta-application with an abstract environment
2019-05-29 11:18:34.238  INFO 11377 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-29 11:18:34.243 ERROR 11377 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pousseCafeRuntime' defined in class path resource [poussecafe/shop/AppConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [poussecafe.runtime.Runtime]: Factory method 'pousseCafeRuntime' threw exception; nested exception is poussecafe.exception.PousseCafeException: Cannot start meta-application with an abstract environment
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1116) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:409) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:337) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at poussecafe.spring.SpringBridge.postProcessBeanFactory(SpringBridge.java:16) ~[classes/:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:181) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at poussecafe.shop.App.main(App.java:12) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.1.5.RELEASE.jar:2.1.5.RELEASE]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [poussecafe.runtime.Runtime]: Factory method 'pousseCafeRuntime' threw exception; nested exception is poussecafe.exception.PousseCafeException: Cannot start meta-application with an abstract environment
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 30 common frames omitted
Caused by: poussecafe.exception.PousseCafeException: Cannot start meta-application with an abstract environment
	at poussecafe.environment.EnvironmentBuilder.checkEnvironment(EnvironmentBuilder.java:189) ~[classes/:na]
	at poussecafe.environment.EnvironmentBuilder.build(EnvironmentBuilder.java:156) ~[classes/:na]
	at poussecafe.runtime.Runtime$Builder.build(Runtime.java:82) ~[classes/:na]
	at poussecafe.shop.AppConfiguration.pousseCafeRuntime(AppConfiguration.java:31) ~[classes/:na]
	at poussecafe.shop.AppConfiguration$$EnhancerBySpringCGLIB$$b12c4d6e.CGLIB$pousseCafeRuntime$0(<generated>) ~[classes/:na]
	at poussecafe.shop.AppConfiguration$$EnhancerBySpringCGLIB$$b12c4d6e$$FastClassBySpringCGLIB$$554b83ed.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at poussecafe.shop.AppConfiguration$$EnhancerBySpringCGLIB$$b12c4d6e.pousseCafeRuntime(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	... 31 common frames omitted```

### PR DESCRIPTION
**Pull request by benoitdevos**
This PR makes the sample shop-app working again. The 2 rest calls now provide the expected results.

Close #69

### CODE REVIEW

File: pousse-cafe-shop-app/src/main/java/poussecafe/shop/domain/mongo/CustomerDataAccess.java [hunk 1]
```diff
@@ -2,10 +2,17 @@
...
 import poussecafe.shop.domain.CustomerId;
 import poussecafe.spring.mongo.storage.MongoDataAccess;
+import poussecafe.spring.mongo.storage.SpringMongoDbStorage;
 
-public class CustomerDataAccess extends MongoDataAccess<CustomerId, CustomerData, String> {
+@DataAccessImplementation(
+        aggregateRoot = Customer.class,
+        dataImplementation = CustomerData.class,
+        storageName = SpringMongoDbStorage.NAME
+)public class CustomerDataAccess extends MongoDataAccess<CustomerId, CustomerData, String> implements poussecafe.shop.domain.CustomerDataAccess<CustomerData> {
```
Comment (gdethier) [inline pousse-cafe-shop-app/src/main/java/poussecafe/shop/domain/mongo/CustomerDataAccess.java]: Put the public class... on the next line

Comment (benoitdevos) [reply pousse-cafe-shop-app/src/main/java/poussecafe/shop/domain/mongo/CustomerDataAccess.java]: Done.
